Assignment1/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
     url(r'^', include('wordbank.urls')),
     url(r'^admin/', admin.site.urls),
     
]

wordbank/urls.py
from django.conf.urls import url

from . import views

app_name = 'wordbank'
urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
#-------------------------search----------------------------------------#
    url(r'^latest/$', views.latest_word.as_view(), name='latest_word'),
#-------------------------add word----------------------------------------#
    url(r'^into_add_page/$', views.into_add_page, name='add_new_word'),
    url(r'^save_new_word/$', views.save_new_word, name='check_error'),
    url(r'^already_word/$', views.save_new_word, name='already_word'),
    url(r'^slips/$', views.save_new_word, name='check_error'),
    
#-------------------------search----------------------------------------#
    url(r'^all/$', views.AllView.as_view(), name='all_word'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='details'),
#-------------------------search----------------------------------------#
    url(r'^search/$', views.word_search, name='search_into_word'),
]

wordbank/models.py
from django.db import models

class Word(models.Model):
    word_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.word_text
    
class Detail(models.Model):
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    type_text= models.CharField(max_length=200)
    mean_text= models.CharField(max_length=200)
    sentence_text= models.CharField(max_length=200)
    

wordbank/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

import csv
import os

from .models import Word, Detail


def home_page(request):
    return render(request,'wordbank/home_page.html')
   
class latest_word(generic.ListView):
    template_name = 'wordbank/latest_word.html'
    context_object_name = 'latest_word_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Word.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Word
    template_name = 'wordbank/details.html'
    def get_queryset(self):
       return Word.objects.filter(pub_date__lte=timezone.now())

class AllView(generic.ListView):
    template_name = 'wordbank/all_word.html'
    context_object_name = 'all_word_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Word.objects.order_by('word_text').all
#----------------- add word -------------------------#


def word_search(request):
    if request.method == 'POST':
        vocab = str(request.POST['search_into_word'])
        if Word.objects.filter(word_text=vocab):
            word = Word.objects.get(word_text=vocab)
            return render(request,'wordbank/search_into_word.html',{'word':word})
        else:
            not_found = ("not found word  : " +'"'+ str(vocab)+'"')
            return render(request,'wordbank/home_page_search.html',{'not_found':not_found})
    return HttpResponseRedirect(reverse('wordbank:home_page'))
           

#----------------------------------------------------------------------
def into_add_page(request):
    return render(request,'wordbank/add_new_word.html')

def save_new_word(request):
    slips = None
    
    if request.method == 'POST':
        add_word = str(request.POST['add_word'])
        add_type = request.POST['add_type']
        add_mean = request.POST['add_mean']
        add_sentence = request.POST['add_sentence']
        add_datetime = timezone.now()

        
        if add_word == "" or add_type == "" or add_mean == "" or add_sentence == "" :#check add data 
            slips = 'please add all field '      
            return render(request,'wordbank/check_error.html',{'slips':slips})

        elif Word.objects.filter(word_text=add_word):
            already_word = Word.objects.get(word_text=add_word)
            already_word.detail_set.create(type_text = add_type,
                                        mean_text =add_mean,
                                        sentence_text=add_sentence  
                                        )
        else:
            new_word = Word(
            word_text = add_word,
            pub_date  = add_datetime
            )
            new_word.save()
            new_word.detail_set.create(type_text = add_type,
                                       mean_text =add_mean,
                                       sentence_text=add_sentence  
                                       )
            
    return HttpResponseRedirect(reverse('wordbank:home_page'))

#-------------------------backup----------------------------------------#
def backup(request):
    list_word = Word.objects.order_by('word_text')
    with open('wordbank/backup/backup.csv', 'w') as csvfile:
        fieldnames = ['word', 'date', 'type', 'mean',  'example']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        for word in list_word:
            for detail in word.detail_set.all():
                writer.writerow({'word':word.word_text, 'date':word.pub_date, 'type':      detail.type_text, 'mean': detail.mean_text,
                 'example': detail.sentence_text})

wordbank/templates/wordbank/add_new_word.html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″ />
		<title>Welcome to wordbank</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/main.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/css/bootstrap.min.css' %}">
	</head>
		<body>
		<div class="header">
			<h1>Add New Word</h1>

		</div><br>
				<form action="{% url 'wordbank:check_error' %}" method="POST">
				{% csrf_token %}
					 <input type="text" name="add_word" placeholder="Word..."><br/>
					 <input type="text" name="add_type" placeholder="Type..."><br/>
					 <input type="text" name="add_mean"  placeholder="Meanning..."><br/>
					 <input type="text" name="add_sentence"  placeholder="example sentence..."><br/>
					 <input class="btn btn-success" type="submit" name= "submit" value="submit" />
					</form>
				<hr size="30">
				<a class="btn btn-info"   href="{% url 'wordbank:latest_word' %}" >Back</a>
		</body>
</html

wordbank/templates/wordbank/all_word.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>show all word</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/css/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/main.css' %}" />
	</head>
		<body>
			<div class="header">
				<h1>All Word Bank</h1>	
			</div><br>		
				{% if all_word_list %}
    				{% for word in all_word_list %}
        				<a href="{% url 'wordbank:details' word.id %}"> {{ word.word_text }}</a>
    				{% endfor %}
				{% else %}
	    			<p>No word are available.</p>
				{% endif %}
				<hr size="30">
				<a   href="{% url 'wordbank:home_page' %}" class="btn btn-info" >Back</a>
		</body>
</html>
	
				
			

wordbank/templates/wordbank/already_word.html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″ />
		<title>Welcome to wordbank</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/main.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/css/bootstrap.min.css' %}">
	</head>
		<body>
		<div class="header">
			<h1>Add new Word</h1>
		</div>
		
		<div class="section">
				<form action="{% url 'wordbank:already_word' %}" method="POST">
				{% csrf_token %}	
					 <input type="text" name="add_word" placeholder="Word..."><br/>
					 <input type="text" name="add_type" placeholder="Type..."><br/>
					 <input type="text" name="add_mean"  placeholder="Meanning..."><br/>
					 <input type="text" name="add_sentence"  placeholder="example sentence..."><br/>
					 <input class="btn btn-success" type="submit" name= "submit" value="submit" />
					</form>
					<p>Error! : {{already}}</p>
					<hr size="30">
						<a href="/" class="btn btn-info" > back</a>	
				</div>
			
		</body>
</html>

wordbank/templates/wordbank/check_error.html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″ />
		<title>Welcome to wordbank</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/main.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/css/bootstrap.min.css' %}">
	</head>
		<body>
		<div class="header">
			<h1>Add New Word</h1>
		</div>
		<div class="section">
				<form action="{% url 'wordbank:check_error' %}" method="POST">
				{% csrf_token %}	
					<input type="text" name="add_word" placeholder="Word..."><br/>
					 <input type="text" name="add_type" placeholder="Type..."><br/>
					 <input type="text" name="add_mean"  placeholder="Meanning..."><br/>
					 <input type="text" name="add_sentence"  placeholder="example sentence..."><br/>
					 <input class="btn btn-success" type="submit" name= "submit" value="submit" />
					</form>
					<p>Error! : {{slips}}</p>
					<hr size="30">
					<a href="/" class="btn btn-info" > back</a>	
				</div>
				
		</body>
</html>

wordbank/templates/wordbank/details.html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″ />
		<title>Welcome to wordbank</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/main.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/css/bootstrap.min.css' %}">
	</head>
		
			
		<body>
		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
				<div class="header">
					<h1>{{ word.word_text }}</h1>
				</div>
				<div class="panel panel-default">
				  		<table class="table table table-bordered " >
				    		<tr class="info" >			
								<td width="10%" ><b><center> type</center> </b></td>
								<td width="30%"><b><center> meaning</center></b></td>
								<td width="30%" ><b><center> sentence</center></b></td> 
							</tr>
				  		</table>
				   {% for detail in word.detail_set.all %}
							<table  class="table  table-bordered table-hover" >
								<tr class="active table-hover">
									<td width="10%">  {{ detail.type_text }}</td>
		    						<td width="30%">{{ detail.mean_text }}</td>
		    						<td width="30%"> {{ detail.sentence_text }}</td>
		    					</tr>
	    				</table>
					{% endfor %}
				</div>
				<script src="{% static 'wordbank/js/jquery.min.js' %}"></script>
    			<!-- Include all compiled plugins (below), or include individual files as needed -->
    			<script src="{% static 'wordbank/js/bootstrap.min.js' %}"></script>
			
		</body>
			<a   href="{% url 'wordbank:latest_word' %}" class="btn btn-info" >Back</a>
</html>

wordbank/templates/wordbank/home_page.html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″ />
		<meta charset="utf-8">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>Welcome to wordbank</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/main.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/css/bootstrap.min.css' %}">
	</head>
		<body>
			<div class="header">
				<h1>Word Bank</h1>
			</div>
			<div>
				<form class="form-inline center " id="brn" action="{% url 'wordbank:search_into_word'%}" method="POST">
						{% csrf_token %}
						<!-- <label> Search Word</label> -->
						<input class="form-control" type="text" name="search_into_word" size="40" placeholder="search word">
						<input class="btn btn-info" type="submit" value="Search">
				</form>
			</div>

			<br><br><br>
				<div class="row">
					<div class="col-md-4"></div>
					<div class="col-md-4">
						<div class="btn-group "  role="group">	
					
					<a   class="btn btn-info" href="/admin/">admin</a>
					<a   class="btn btn-info" href="{% url 'wordbank:all_word' %}">all word</a>
					<a   class="btn btn-info" href="{% url 'wordbank:add_new_word' %}">add word</a>
					<a   class="btn btn-info" href="{% url 'wordbank:latest_word' %}">latest word</a>

				</div>
					</div>
					<div class="col-md-4"></div>
				</div>
				

				<script src="{% static 'wordbank/js/jquery.min.js' %}"></script>
    			<!-- Include all compiled plugins (below), or include individual files as needed -->
    			<script src="{% static 'wordbank/js/bootstrap.min.js' %}"></script>
			
		</body>
<html>

wordbank/templates/wordbank/home_page_search.html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″ />
		<meta charset="utf-8">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>Welcome to wordbank</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/main.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/css/bootstrap.min.css' %}">
	</head>
		<body>
			<div class="header">
				<h1>Word Bank</h1>
			</div>
			<div>

				<form class="form-inline center " id="brn" action="{% url 'wordbank:search_into_word'%}" method="POST">
						{% csrf_token %}
						<!-- <label> Search Word</label> -->

						<input class="form-control" type="text" name="search_into_word" size="40" placeholder="search word">


						<input class="btn btn-info" type="submit" value="Search">
						<br><br><br>
						<p >{{not_found}}</p>
						<h1><p> Try Again</p></h1>
				</form>

			</div>

				<script src="{% static 'wordbank/js/jquery.min.js' %}"></script>
    			<!-- Include all compiled plugins (below), or include individual files as needed -->
    			<script src="{% static 'wordbank/js/bootstrap.min.js' %}"></script>
			
		</body>
<html>

wordbank/templates/wordbank/latest_word.html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″ />
		<title>Welcome to wordbank</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/main.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/css/bootstrap.min.css' %}">
	</head>
		<body>
			<div class="header">
				<h1>Latest Word</h1>
			</div>
			<ul>
				{% if latest_word_list %}
    				{% for word in latest_word_list %}	
       					<li><h1><a href="{% url 'wordbank:details' word.id %}">{{ word.word_text }}</a></h1></li>
       				{% endfor %}
				{% else %}
    			<p>No word are available.</p>
				{% endif %}
				
				</ul>
				<hr size="30">
				<a href="/" class="btn btn-info"   >back</a>
			
				
		</body>
</html>

wordbank/templates/wordbank/search_into_word.html
<!DOCTYPE html>
<html>
	<head>
        <title>Search Result</title>
        {% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/main.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'wordbank/css/bootstrap.min.css' %}">
	</head>
	<meta http-equiv=”Content-Type” content=”text/html; charset=UTF-8″>
		<body>
			<div class="header">
				<h1>{{ word.word_text }}{{not_found}}</h1>
			</div>
			
				{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
		
			<div class="panel panel-default">
				  		<table class="table table table-bordered " >
				    		<tr class="info" >			
								<td width="10%" ><b><center> type</center> </b></td>
								<td width="30%"><b><center> meaning</center></b></td>
								<td width="30%" ><b><center> sentence</center></b></td> 
							</tr>
				  		</table>
				   {% for detail in word.detail_set.all %}
							<table  class="table  table-bordered table-hover" >
								<tr class="active table-hover">
									<td width="10%">  {{ detail.type_text }}</td>
		    						<td width="30%">{{ detail.mean_text }}</td>
		    						<td width="30%"> {{ detail.sentence_text }}</td>
		    					</tr>
	    				</table>
					{% endfor %}
				</div>	
			
				<hr size="30">
				<a href="{% url 'wordbank:home_page'  %}" class="btn btn-info"  >back</a>
		</body>
</html>